# Generated by Django 2.2.4 on 2019-08-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=0, help_text='in cents'),
        ),
    ]
